config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('user.urls')),
]

user/urls.py
from operator import ne
from user import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
  path('', view=views.mainSearch, name="main"),
  path('mypage/', view=views.myPage, name="myPage"),

  path('myInfo/', view=views.myInfo, name="myInfo"),
  path('updateInfo/', view=views.updateInfo, name="updateInfo"),
  path('myInfo/register/', view=views.myInfoRegister, name="myInfoRegister"),
  path('register/', views.certificationRegister, name='certificationRegister'),
  path('mypage/<int:pk>/', views.certDetail, name='certDetail'),
  path('mypage/<int:pk>/update/', views.certUpdate, name='certUpdate'),
  path('mypage/<int:pk>/delete/', views.certDelete, name='certDelete'),
  path('register/addMusicAjax/', views.addMusicAjax, name='addMusicAjax'),

  path('search/',views.searchResult, name='search'),
  path('search/addMusicAjax/', views.addMusicAjax, name='addMusicAjax'),
  path('search/myFeed',views.searchMyFeed, name='searchMyFeed'),
  path('search/likedFeed',views.searchLikedFeed, name='searchLikedFeed'),
  path('deleteFeed/<int:pk>',views.deleteFeed, name="deleteFeed"),
  path('updateFeed/<int:pk>', views.updateFeed, name="updateFeed"),
  path('updateFeed/addMusicAjax/', views.addMusicAjax, name='addMusicAjax'),
  path('feed/<int:pk>/', views.feedDetail, name="feedDetail"),
  path('search/<int:pk>/like/', views.feedLike, name='feedLike'),
  path('list/',views.feedList, name='feedList'),
  path('list/addMusicAjax/', views.addMusicAjax, name='addMusicAjax'),
  
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/certDetail.html
{% extends 'searchBase.html' %}
{% load static %}
{% block content %}

<div class="certDetail-title"><a href="{% url 'user:myPage' %}"><img class="RE-mypage"
			src="{% static 'img/moreCertBtn.png' %}" alt="" style="transform: rotate(-180deg)"></a>나의 뮤직 카드</div>

<div class="certDetail-container">
	<div class="certDetail-img">
		<div class="certDetail-img-front"><img src="{{ cert.albumImg.url }}" height="440" width="400"></div>
		<div class="certDetail-img-back"
			style='background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url({{ cert.albumImg.url }})'>
			<img class="cert-stamp" src="{%static 'img/note.png'%}" alt="">
		</div>
	</div>
	<div class="certDetail-info">
		<div class="music-info listen-box">
			<div class="listen-box">
				<span class="index boldfont listening">Listening</span>
				<br />
				<span class="boldfont listen-date">{{cert.createdDate | date:'Y.m.d'}} ~</span>
			</div>
		</div>
		<div class="music-info">
			<div class="index">곡</div>
			<div>{{cert.music}}</div>
		</div>
		<div class="music-info">
			<div class="index">아티스트</div>
			<div>{{cert.artist}}</div>
		</div>

		<div class="music-info sns-and-buttons">
			<div class="sns-all">
				<div class="sns-box"><a id="btnTwitter" class="link-icon twitter" href="javascript:shareTwitter();"><img
							src="{%static 'img/icon-twitter.png'%}" alt=""></a></div>
				<div class="sns-box"><a id="btnFacebook" class="link-icon facebook" href="javascript:shareFacebook();"><img
							src="{%static 'img/icon-facebook.png'%}" alt=""></a></div>
				<div class="sns-box"><a id="btnKakao" class="link-icon kakao" href="javascript:shareKakao();"><img
							src="{%static 'img/icon-kakao.png'%}" alt=""></a></div>
			</div>

			{% if request.user != cert.userId %}
			{% else %}
			<div class="certDetail-buttons">
				<button><a href="{% url 'user:certUpdate' cert.id %}">수정</a></button>
				<button><a href="{% url 'user:certDelete' cert.id %}">삭제</a></button>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/SNS.js' %}">

</script>
<script src="//developers.kakao.com/sdk/js/kakao.min.js"></script>
<script>
	const urlforKakao = window.location.href
	function shareKakao() {

		// 사용할 앱의 JavaScript 키 설정
		Kakao.init('1706f71509ba01819512832811f52204')

		// 카카오링크 버튼 생성
		Kakao.Link.createDefaultButton({
			container: '#btnKakao', // 카카오공유버튼ID
			objectType: 'feed',
			content: {
				title: "야드Yard", // 보여질 제목
				description: "Yard | 야, 들어봐 너도!", // 보여질 설명
				imageUrl: urlforKakao, // 콘텐츠 URL
				link: {
					mobileWebUrl: urlforKakao,
					webUrl: urlforKakao,
				}
			}
		});
	}
</script>

{% endblock %}

templates/feedSearch.html
{% extends "searchBase.html" %}
{% load static %}
{% block content %}
{% load bootstrap4 %}
<div class="feed-result">
  <p class="my_search_text">검색 결과: <b>"{{query}}"</b></p>
</div>


<div class="feedNtag-container">
<div class="feed-list white-form" id ='feed-list'>
  <div class="feed-addContainer">
    <div class="feed-add">
      {% if request.user.userImg %}
      <img src="{{ request.user.userImg.url }}" class="feed--userImg" alt="userImg">
      {% else %}
      <img src="{% static 'img/default.jpeg' %}" class="feed--userImg" alt="userImg">
      {% endif %}
      <input  type="text" type="submit" placeholder="글을 작성하려면 누르세요" data-bs-toggle="modal" data-bs-target="#feedForm" data-bs-backdrop="static" data-bs-keyboard="false"/>

    </div>
    {% if request.user.id %}
    <div class="feed-filterBtn">
      <a href="{% url 'user:feedList' %}"><button class="feed-list-btn float-on-hover" value="myFeed">전체 글 보기</button></a>
      <a href="{% url 'user:searchMyFeed' %}"><button class="feed-my float-on-hover" value="myFeed">내가 쓴 글</button></a>
      <a href="{% url 'user:searchLikedFeed' %}"><button class="feed-like float-on-hover">좋아하는 글</button></a>
    </div>
    {% endif %}
  </div>

  {% for feed in feeds %}
  


  {% if request.user.id != feed.userId.id%}
  <div class="feed-container">
    <div class="feed--userInfo">
      {% if feed.userId.userImg %}
      <img src="{{ feed.userId.userImg.url }}" class="feed--userImg" alt="userImg">
      {% else %}
      <img src="{% static 'img/default.jpeg' %}" class="feed--userImg" alt="userImg">
      {% endif %}
      <p class="feed--userName">{{feed.userId.nickName}}</p>
    </div>
    <div class="feed--content white-form">
      <div class="feed--content-top">
        <div class="feed--content-left">
          <p class='feed-title'><img style="padding: 0.8rem 1rem 0 0;" src="{% static 'img/purpleNote.png' %}" height="27" alt="">{{feed.artist}} - {{feed.music}}</p>
          <p class='feed-content text-break'>{{feed.content}}</p>
          {% if feed.feedImg %}
          <img src="{{feed.feedImg.url}}" alt="">
          {% endif %}
        </div>
        <div class="feed--content-right">
          <p style="font-size: 1.4rem;">{{feed.createdDate|date:"Y-m-d H:i"}}</p>
          <div class="feed-heart">  
            {% if request.user.is_authenticated %}
            <div>
              {% if user in feed.like_users.all %}
              <i class="fas fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
              {% else %}
              <i class="far fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
              {% endif %}
            </div> 
              <div id="like-count-{{ feed.id }}">{{ feed.like_users.count }}</div>
            {% endif %}
            </div>
        </div>
      </div>
      <div class="feed--content-bottom">
        <div class="feed-hashtagList feed-{{feed.id}}">
          {% for tag in feed.tags.all %}
          <div class="hashtag--btn">{{tag}}</div>
          {% endfor %}

          {% if feed.inputTags %}
          <div id ="newHash" style="display:none";>{{feed.inputTags}}</div>
          <script>
            addInputTag();

            function addInputTag() {
              const usersTag = document.querySelector(".feed-{{feed.id}} #newHash").innerHTML;
              const choiceTags = document.querySelectorAll('.hashtag--btn');
              let choiceTagList = []
              for (let i=0; i < choiceTags.length; i++) {
              let choiceTag = choiceTagList.push(choiceTags[i].innerText);
              }
              const hashTagArray = usersTag.split(' ');
              let uniqueTagArray = [];
              hashTagArray.forEach((element) => {
                  if (!uniqueTagArray.includes(element)) {
                    uniqueTagArray.push(element);
                  }
              });
            

              for (let i=0; i < uniqueTagArray.length; i++) {
                if (!(choiceTagList.includes(uniqueTagArray[i]))) {
                  const newDiv = document.createElement('div');
                  newDiv.setAttribute("class", "hashtag--btn");
                  const newText = document.createTextNode(uniqueTagArray[i]);
                  newDiv.appendChild(newText);
                  const tagDiv = document.querySelector('.feed-hashtagList.feed-{{feed.id}}');
                  console.log(tagDiv)
                  tagDiv.append(newDiv);
                }
                else {
                }
              };
            };
          </script>
          {% endif %}
        </div>
      </div>
      
    </div>
  </div>
  
  {% else %}
  <div class="feed-container">
  <div class="feed--content-my white-form">
    <div class="feed--content-top">
      <div class="feed--content-left">
        <p class='feed-title'><img style="padding: 0.8rem 1rem 0 0;" src="{% static 'img/purpleNote.png' %}" height="27" alt="">{{feed.artist}} - {{feed.music}}</p>
        <p class='feed-content text-break'>{{feed.content}}</p>
        {% if feed.feedImg %}
        <img src="{{feed.feedImg.url}}"  alt="">
        {% endif %}
        
      </div>
      <div class="feed--content-right">
        <div class="feed-twobtn">
          <p>{{feed.createdDate|date:"Y-m-d H:i"}}</p>
          &nbsp;&nbsp;|&nbsp;
          <a href="{% url 'user:updateFeed' feed.id %}">수정</a>
          &nbsp;&nbsp;|&nbsp;
          <a href="{% url 'user:deleteFeed'  feed.id %}">삭제</a>
        </div>
        <div class="feed-heart">  
            {% if request.user.is_authenticated %}
            <div>
              {% if user in feed.like_users.all %}
              <i class="fas fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
              {% else %}
              <i class="far fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
              {% endif %}
            </div>
              <div id="like-count-{{ feed.id }}">{{ feed.like_users.count }}</div>
            {% endif %}
        </div>
      </div>
    </div>
    <div class="feed--content-bottom">
       
      <div class="feed-hashtagList feed-{{feed.id}}">
        {% for tag in feed.tags.all %}
        <div id="hashTag" class="hashtag--btn">{{tag}}</div>
        {% endfor %}
        {% if feed.inputTags %}
          <div id ="newHash" style="display:none";>{{feed.inputTags}}</div>
          <script>
            addInputTag();

            function addInputTag() {
              const usersTag = document.querySelector(".feed-{{feed.id}} #newHash").innerHTML;
              const choiceTags = document.querySelectorAll('.hashtag--btn');
              let choiceTagList = []
              for (let i=0; i < choiceTags.length; i++) {
              let choiceTag = choiceTagList.push(choiceTags[i].innerText);
              }
              const hashTagArray = usersTag.split(' ');
              let uniqueTagArray = [];
              hashTagArray.forEach((element) => {
                  if (!uniqueTagArray.includes(element)) {
                    uniqueTagArray.push(element);
                  }
              });
            

              for (let i=0; i < uniqueTagArray.length; i++) {
                if (!(choiceTagList.includes(uniqueTagArray[i]))) {
                  const newDiv = document.createElement('div');
                  newDiv.setAttribute("class", "hashtag--btn");
                  const newText = document.createTextNode(uniqueTagArray[i]);
                  newDiv.appendChild(newText);
                  const tagDiv = document.querySelector('.feed-hashtagList.feed-{{feed.id}}');
                  console.log(tagDiv)
                  tagDiv.append(newDiv);
                }
                else {
                }
              };
            };
          </script>
        {% endif %}
      </div>
    </div>
    
  </div>
  <div class="feed--userInfo">
    {% if feed.userId.userImg %}
    <img src="{{ feed.userId.userImg.url }}" class="feed--userImg" alt="userImg">
    {% else %}
    <img src="{% static 'img/default.jpeg' %}" class="feed--userImg" alt="userImg">
    {% endif %}
    <p class="feed--userName">{{feed.userId.nickName}}</p>
  </div>
</div>
  {% endif %}
  
  {% empty %}

  <div class="empty-feed">
    <p class="my_search_text">
      게시글이 아직 없네요, 게시글을 생성해보세요! &nbsp
    </p>
    <p><a href="{% url 'user:main' %}">메인으로 이동하기</a></p>
  </div>

  {% endfor %}
</div>
<!--
<div class="tag-list tagClose white-form" id = 'tag-list'>
  <h1>추천 태그</h1>
  {% for feed in feeds %}
  {% for tag in feed.tags.all %}
  <ul>{{tag}}</ul>
  {% endfor %}
  {% endfor %}
</div>-->
<div id ="tag-list-btn" style="visibility:hidden" class="tag-list-btn">추천태그</div>
<div class="tag-list tagClose" id = 'tag-list'  style="visibility:hidden">
  {% for feed in feeds %}
  {% for tag in feed.tags.all %}
  <ul class="tag">{{tag}}</ul>
  {% endfor %}
  {% endfor %}
</div>
</div>



<!-- 피드 등록 폼 modal -->
<div id="feedForm" class="modal fade " style="color: black;" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="color: black;">피드 등록하기</h5>
        <a href="{% url 'user:feedList' %}" ><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button ></a>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <form class="searchDiv" action="methods" enctype="multipart/form-data">
            <label for="songinfo">음악 검색</label>
            <div>
              <input type="text" id="songinfo" style="width: 140%;" class="whatToSearch float-on-hover" placeholder="검색" autocomplete="off" />
              <input type="text" style="display: none" />
              <button type="button" class="float-on-hover" style="width: 80%;" onclick="addMusicList()">검색</button>
            </div>
          </form>
        </div>
        <div class="musicListList"></div>

        <button id="registerMusic" class="saveFeedForm float-on-hover"  onclick="registerMusic()">노래 등록</button>
        <form method="POST" class="post-form" enctype="multipart/form-data">

          {% csrf_token %} {{ form.as_p }}

          <button type="submit" class="saveFeedForm float-on-hover">등록</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock %}
{% block js %}
<script src='{% static "js/feedpage.js"%}'></script>
<script src='{% static "js/feedLike.js"%}'></script>
<script src = '{%static "js/feed1.js" %}'>

</script>
{% endblock %}

templates/updateFeed.html
{% extends "searchBase.html" %}
{% load static %}
{% block content %}
{% load bootstrap4 %}
<div class="feed-result">
  <p class="my_search_text">검색 결과: <b>"{{query}}"</b></p>
  <p><a href="{% url 'user:main' %}">메인으로 이동하기</a></p>
</div>


<div class="feedNtag-container">
  <div class="feed-list white-form" id ='feed-list'>
    <div class="feed-addContainer">
      <div class="feed-add">
        {% if request.user.userImg %}
        <img src="{{ request.user.userImg.url }}" class="feed--userImg" alt="userImg">
        {% else %}
        <img src="{% static 'img/default.jpeg' %}" class="feed--userImg" alt="userImg">
        {% endif %}
        <input  type="text" type="submit" placeholder="글을 작성하려면 누르세요" data-bs-toggle="modal" data-bs-target="#feedForm" data-bs-backdrop="static" data-bs-keyboard="false"/>
  
      </div>
      {% if request.user.id %}
      <div class="feed-filterBtn">
        <a href="{% url 'user:feedList' %}"><button class="feed-list-btn float-on-hover" value="myFeed">전체 글 보기</button></a>
        <a href="{% url 'user:searchMyFeed' %}"><button class="feed-my float-on-hover" value="myFeed">내가 쓴 글</button></a>
        <a href="{% url 'user:searchLikedFeed' %}"><button class="feed-like float-on-hover">좋아하는 글</button></a>
      </div>
      {% endif %}
    </div>
  
    {% for feed in feeds %}
  
    {% if request.user.id != feed.userId.id%}
    <div class="feed-container">
      <div class="feed--userInfo">
        {% if feed.userId.userImg %}
        <img src="{{ feed.userId.userImg.url }}" class="feed--userImg" alt="userImg">
        {% else %}
        <img src="{% static 'img/default.jpeg' %}" class="feed--userImg" alt="userImg">
        {% endif %}
        <p class="feed--userName">{{feed.userId.nickName}}</p>
      </div>
      <div class="feed--content white-form">
        <div class="feed--content-top">
          <div class="feed--content-left">
            <p class='feed-title'><img style="padding: 0.8rem 1rem 0 0;" src="{% static 'img/purpleNote.png' %}" height="27" alt="">{{feed.artist}} - {{feed.music}}</p>
            <p class='feed-content text-break'>{{feed.content}}</p>
            {% if feed.feedImg %}
            <img src="{{feed.feedImg.url}}" alt="">
            {% endif %}
          </div>
          <div class="feed--content-right">
            <p style="font-size: 1.4rem;">{{feed.createdDate|date:"Y-m-d H:i"}}</p>
            <div class="feed-heart">  
              {% if request.user.is_authenticated %}
              <div>
                {% if user in feed.like_users.all %}
                <i class="fas fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
                {% else %}
                <i class="far fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
                {% endif %}
              </div> 
                <div id="like-count-{{ feed.id }}">{{ feed.like_users.count }}</div>
              {% endif %}
              </div>
          </div>
        </div>
        <div class="feed--content-bottom">
          <div class="feed-hashtagList feed-{{feed.id}}">
            {% for tag in feed.tags.all %}
            <div class="hashtag--btn">{{tag}}
            </div>
            {% endfor %}
            {% if feed.inputTags %}
          <div id ="newHash" style="display:none";>{{feed.inputTags}}</div>
          <script>
            addInputTag();

            function addInputTag() {
              const usersTag = document.querySelector(".feed-{{feed.id}} #newHash").innerHTML;
              const choiceTags = document.querySelectorAll('.hashtag--btn');
              let choiceTagList = []
              for (let i=0; i < choiceTags.length; i++) {
              let choiceTag = choiceTagList.push(choiceTags[i].innerText);
              }
              const hashTagArray = usersTag.split(' ');
              let uniqueTagArray = [];
              hashTagArray.forEach((element) => {
                  if (!uniqueTagArray.includes(element)) {
                    uniqueTagArray.push(element);
                  }
              });
            

              for (let i=0; i < uniqueTagArray.length; i++) {
                if (!(choiceTagList.includes(uniqueTagArray[i]))) {
                  const newDiv = document.createElement('div');
                  newDiv.setAttribute("class", "hashtag--btn");
                  const newText = document.createTextNode(uniqueTagArray[i]);
                  newDiv.appendChild(newText);
                  const tagDiv = document.querySelector('.feed-hashtagList.feed-{{feed.id}}');
                  console.log(tagDiv)
                  tagDiv.append(newDiv);
                }
                else {
                }
              };
            };
          </script>
          {% endif %}
          </div>
        </div>
        
      </div>
    </div>
    
    {% else %}
    <div class="feed-container">
    <div class="feed--content-my white-form">
      <div class="feed--content-top">
        <div class="feed--content-left">
          <p class='feed-title'><img style="padding: 0.8rem 1rem 0 0;" src="{% static 'img/purpleNote.png' %}" height="27" alt="">{{feed.artist}} - {{feed.music}}</p>
          <p class='feed-content text-break'>{{feed.content}}</p>
          {% if feed.feedImg %}
          <img src="{{feed.feedImg.url}}"  alt="">
          {% endif %}
          
        </div>
        <div class="feed--content-right">
          <div class="feed-twobtn">
            <p>{{feed.createdDate|date:"Y-m-d H:i"}}</p>
            &nbsp;&nbsp;|&nbsp;
            <a href="{% url 'user:updateFeed' feed.id %}">수정</a>
            &nbsp;&nbsp;|&nbsp;
            <a href="{% url 'user:deleteFeed'  feed.id %}">삭제</a>
          </div>
          <div class="feed-heart">  
              {% if request.user.is_authenticated %}
              <div>
                {% if user in feed.like_users.all %}
                <i class="fas fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
                {% else %}
                <i class="far fa-heart likeButton" data-id="{{ feed.id }}" style="color:red"></i>
                {% endif %}
              </div>
                <div id="like-count-{{ feed.id }}">{{ feed.like_users.count }}</div>
              {% endif %}
          </div>
        </div>
      </div>
      <div class="feed--content-bottom">
         
        <div class="feed-hashtagList feed-{{feed.id}}">
          {% for tag in feed.tags.all %}
          <div id="hashTag" class="hashtag--btn">{{tag}}</div>
          {% endfor %}
          {% if feed.inputTags %}
          <div id ="newHash" style="display:none";>{{feed.inputTags}}</div>
          <script>
            addInputTag();

            function addInputTag() {
              const usersTag = document.querySelector(".feed-{{feed.id}} #newHash").innerHTML;
              const choiceTags = document.querySelectorAll('.hashtag--btn');
              let choiceTagList = []
              for (let i=0; i < choiceTags.length; i++) {
              let choiceTag = choiceTagList.push(choiceTags[i].innerText);
              }
              const hashTagArray = usersTag.split(' ');
              let uniqueTagArray = [];
              hashTagArray.forEach((element) => {
                  if (!uniqueTagArray.includes(element)) {
                    uniqueTagArray.push(element);
                  }
              });
            

              for (let i=0; i < uniqueTagArray.length; i++) {
                if (!(choiceTagList.includes(uniqueTagArray[i]))) {
                  const newDiv = document.createElement('div');
                  newDiv.setAttribute("class", "hashtag--btn");
                  const newText = document.createTextNode(uniqueTagArray[i]);
                  newDiv.appendChild(newText);
                  const tagDiv = document.querySelector('.feed-hashtagList.feed-{{feed.id}}');
                  console.log(tagDiv)
                  tagDiv.append(newDiv);
                }
                else {
                }
              };
            };
          </script>
          {% endif %}
        </div>
      </div>
      
    </div>
    <div class="feed--userInfo">
      {% if feed.userId.userImg %}
      <img src="{{ feed.userId.userImg.url }}" class="feed--userImg" alt="userImg">
      {% else %}
      <img src="{% static 'img/default.jpeg' %}" class="feed--userImg" alt="userImg">
      {% endif %}
      <p class="feed--userName">{{feed.userId.nickName}}</p>
    </div>
  </div>
    {% endif %}
    
    {% empty %}
  
    <div class="empty-feed">
      <p class="my_search_text">
        게시글이 아직 없네요, 게시글을 생성해보세요! &nbsp
      </p>
      <p><a href="{% url 'user:main' %}">메인으로 이동하기</a></p>
    </div>
  
    {% endfor %}
  </div>
  <!--
  <div class="tag-list tagClose white-form" id = 'tag-list'>
    <h1>추천 태그</h1>
    {% for feed in feeds %}
    {% for tag in feed.tags.all %}
    <ul>{{tag}}</ul>
    {% endfor %}
    {% endfor %}
  </div>-->
  <div id ="tag-list-btn" style="visibility:hidden" class="tag-list-btn">추천태그</div>
  <div class="tag-list tagClose" id = 'tag-list'  style="visibility:hidden">
    {% for feed in feeds %}
    {% for tag in feed.tags.all %}
    <ul class="tag">{{tag}}</ul>
    {% endfor %}
    {% endfor %}
  </div>
  </div>



<!-- 피드 등록 폼 modal -->
<div id="feedForm" class="modal fade " style="color: black;" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="color: black;">피드 수정하기</h5>
        <a href="{% url 'user:feedList' %}" ><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button ></a>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <form class="searchDiv" action="methods" enctype="multipart/form-data">
            <label for="songinfo">음악 검색</label>
            <div>
              <input type="text" id="songinfo" style="width: 140%;" class="whatToSearch float-on-hover" placeholder="검색" autocomplete="off" />
              <input type="text" style="display: none" />
              <button type="button" class="float-on-hover" style="width: 80%;" onclick="addMusicList()">검색</button>
            </div>
          </form>
        </div>
        <div class="musicListList"></div>

        <button id="registerMusic" class="saveFeedForm float-on-hover"  onclick="registerMusic()">노래 등록</button>
        <form method="POST" class="post-form" enctype="multipart/form-data">

          {% csrf_token %} {{ form.as_p }}

          <button type="submit" class="saveFeedForm float-on-hover">수정</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock %}
{% block js %}
<script src='{% static "js/feedpage.js"%}'></script>
<script src='{% static "js/feedLike.js"%}'></script>
<script src = '{%static "js/feed2.js" %}'>

</script>
{% endblock %}